### PR TITLE
Add neisseria subwf: ngmaster and meningotype

### PR DESCRIPTION
**Pull request by kapsakcj**
~~Setting as a draft until testing in Terra is complete and when `staphb/ngmaster:1.0.0` docker image is available~~

staphb docker image is available `staphb/ngmaster:1.0.0`, just doing one final test in Terra with new docker image

This PR:

- alters the meningotype task (for N. meningitidis):
  - by default run all typing options (except `mlst` which is done via `ts_mlst` task which uses more up-to-date dbs)
  - produce new String outputs for the serogroup and each allele number
  - runtime now uses `cpu` input variable
  - removed optional inputs for toggling various typing. We want all to run all the time (except mlst)
- alters ngmaster task (for N. gonnorhoeae):
  - docker default is `kapsakcj/ngmaster:1.0.0`, need to change this to `staphb/ngmaster:1.0.0` when available
  - altered output TSV filename to be more descriptive
  - added code to parse output TSV for MLSequence Types from 2 schemes (NG-MAST and NG-STAR). Additionally parsing allele numbers that correspond w each scheme.
  - added numerous String outputs for each MLST and allele numbers
  - runtime now uses `cpu` input variable
- task_gambit.wdl edited to designate 2 new `merlin_tag`'s: `Neisseria gonorrhoeae` and `Neisseria meningitidis`
- export_taxon_tables task edited to accept new inputs from ngmaster & meningotype tasks
- `wf_merlin_magic.wdl` edited to run:
  - `ngmaster` when merlin_tag is set to `Neisseria gonorrhoeae`
  - `meningotype` when merlin_tag is set to `Neisseria meningitidis`
  - all new outputs added to workflow outputs
- Both `workflows/wf_theiaprok_illumina_pe.wdl` and `workflows/wf_theiaprok_illumina_se.wdl` were edited to have new ngmaster & meningotype outputs
  - also added new outputs as inputs for export_taxon_tables task

Testing:

- [x] Illumina_PE on both species - [Successful Terra workflow (albeit with kapsakcj/ngmaster:1.0.0)](https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/curtis_sandbox/job_history/85980f46-0bee-4938-9912-9fb26dc0982e); will add link to second test w staphb/ngmaster:1.0.0 docker image soon)
- [x] Illumina_PE - [Successful Terra workflow N. gonnorhoeae with updated `staphb/ngmster:1.0.0` docker image](https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/curtis_sandbox/job_history/7b5d155e-9759-4814-8ba7-ea7ba24ef781)
- [x] Illumina_SE on both species- [Successful Terra workflow](https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/curtis_sandbox/job_history/e35f349f-57b3-4ab2-a19a-d065d5cd1f51)

CC @cimendes

### CODE REVIEW

**Comment by cimendes** [comment]
@kapsakcj a retrigger seems to have done the trick :)

**Review by kevinlibuit — COMMENTED** [review]
Changes look solid! Great job, @kapsakcj and @cimendes.

Having issues signing into Terra atm, but will be able to give this a final approval and merge things to main once I'm able to check out those test runs in a workspace.

**Review by kevinlibuit — APPROVED** [review]

**Comment by cimendes** [comment]
@kevinlibuit @kapsakcj can the branch be deleted?

**Comment by kapsakcj** [comment]
I'll delete it now. Usually wait to delete them, but since we haven't told any users about this branch I doubt anyone is using it. And if they are, they can switch to main 👍

**Comment by sage-wright** [comment]
Closes #205

**Pull request merged**
