### PR TITLE
adds p. aeruginosa subworkflow and pasty for serogrouping

### PR DESCRIPTION
**Pull request by jrotieno**
This PR adds a subworkflow to merlin_magic for _Pseudomonas aeruginosa_, which runs the tool pasty (https://github.com/rpetit3/pasty) for serogrouping.

If the gambit predicted taxon is "Pseudomonas aeruginosa", it triggers the _Pseudomonas aeruginosa_ subworkflow.

This PR applies to both the theiaprok single and paired end workflows.

This adds eight new output columns to the export taxon tables:
```wdl
    String? pasty_serogroup = merlin_magic.pasty_serogroup
    Float? pasty_serogroup_coverage = merlin_magic.pasty_serogroup_coverage
    Int? pasty_serogroup_fragments = merlin_magic.pasty_serogroup_fragments
    File? pasty_summary_tsv = merlin_magic.pasty_summary_tsv
    File? pasty_blast_hits = merlin_magic.pasty_blast_hits
    File? pasty_all_serogroups = merlin_magic.pasty_all_serogroups
    String? pasty_version = merlin_magic.pasty_version
    String? pasty_docker = merlin_magic.pasty_docker
```
We have tested on both miniwdl and Terra.

### CODE REVIEW

**Comment by kapsakcj** [comment]
Tested both PE and SE workflow on Terra and everything ran as expected, including the export_taxon_tables task ✔️ 

I'll take one more look at the code changes and approve if all looks good.

Nice work, James!

**Review by kapsakcj — APPROVED** [review]
Code looks good and tests pass in Terra for both PE and SE workflows 👍

**Review by emmadoughty — APPROVED** [review]
Outputs in Terra look good, checked outputs and skimmed the code.

This looks really great! Congrats on your first PR, James!

**Comment by jrotieno** [comment]
Thank you both!

**Pull request merged**
