### PR TITLE
Update gambit task output

### PR DESCRIPTION
**Pull request by jlumpe**
Not sure how Terra reports outputs which are structs/objects, maybe should merge this into its own branch.

### CODE REVIEW

**Comment by kevinlibuit** [comment]
Ah, I think you're right: since there are a few labs using this dev branch and we're not sure how this PR will impact functionality on Terra, I created a separate branch: [mjl-gambittaxon-dev](https://github.com/theiagen/public_health_bacterial_genomics/tree/mjl-gambittaxon-dev). Can you make request the merge there?

**Comment by jlumpe** [comment]
Could you reset the `mjl` branch to point to `kgl-gambit-update-dev`? There are a lot of merge conflicts between that one and `main`.

**Comment by jlumpe** [comment]
Should be good to go

**Comment by kevinlibuit** [comment]
Thanks. Merging now and will be able to run things on Terra soon

**Pull request merged**
