### PR TITLE
reorder snp matrix

### LINKED ISSUE #133: snp-dists output matrix not ordered correctly
We need to do hierarchical clustering instead of a simple bash sort which is unfortunate. Would require making a new task because the easiest solution right now looks to be using scipy.cluster.hierarchy.XXX and the current docker doesn't have that

### PR DESCRIPTION
**Pull request by sage-wright**
This PR will close #133 by using the list of terminal ends generated by kSNP3 to reorder the SNP matrix produced in snp-dists. 

This is accomplished by: 
- removing the current method of ordering the SNP matrix from the `snp_dists` task
- creating a new task (task `reorder_matrix` in `task_snp_dists.wdl`) that will, given a newick tree and snp matrix:
  - use the newick tree to extract a list of the ordered terminal ends
  - reorder the snp matrix with that list
  - return the reordered snp matrix
- calling the new task twice in the kSNP3 workflow for both the pan and core trees.

### CODE REVIEW

**Comment by emmadoughty** [comment]
The matrix order looks really great for viewing in excel. With a conditional colour scale it looks really pretty as well as informative!
image


I have noticed that the tip order doesn't match the vertical order of tips in the KSNP3 phylogeny I generated in the same wf, so it's still not possible to view this matrix nicely against the tree. Throwing this into Phandango gave me this below...
image


Would it be possible to look into issue occurring with the tip order?

**Review by emmadoughty — APPROVED** [review]
Great work! Some testing notes and suggestions below:

- Tested on the *Salmonella* dataset and *Acinetobacter* dataset (sample names = numeric-only) in Doughty_Sandbox
    - Functions perfectly to mirror the vertical order of terminal nodes from the kSNP3 tree in the SNP-matrix row and column order.
- Input/output file names are unchanged and look great
- Beautifully commented code!
- The code itself looks good as far as I understand it
- It would be great to provide SNP matrices as CSV files with Phandango formatting so that users can use Phandango to visualize their trees (requires appending `:c1` to the end of each column header containing metadata, see [https://github.com/jameshadfield/phandango/wiki/Input-data-formats#metadata](https://github.com/jameshadfield/phandango/wiki/Input-data-formats#metadata))

Suggestions outside this PR

- Add reordering of SNP-matrix to SNP-dists task in Snippy_Tree wf (in PHB)
- Re-root the trees output kSNP3/Snippy_Tree for nice visualization/easier interpretation (see https://github.com/theiagen/public_health_bacterial_genomics/issues/200)

**Comment by sage-wright** [comment]
The latest commits implement the following changes:

- the `reorder_matrix` task will now output: 
  - the ordered matrix, 
  - a midpoint rooted tree, and
  - a midpoint-rooted ordered matrix 

Phandango coloring is automatically applied to all column headers in matrices (`:c1`); these matrix files are now .csv files for easy transfer to phandango,
- the `summarize_data` task now will digest a _space-separated_ list of column names, parse through those column contents, then output a csv with presence/absence for each item in those columns. There is a Boolean option to turn off Phandango coloring (which will color each column differently). See this for example output: [example_summarized_data.csv](https://github.com/theiagen/public_health_bacterial_genomics/files/10451129/example_summarized_data.csv)

See https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Wright_PHBG_Sandbox/workflows/theiagen-validations/kSNP3 for help regarding usage of this task.

- the `reorder_matrix` and `summarize_data` tasks have been added to the kSNP3 and Core_Gene_SNP workflows
- the `summarize_data` task has been added to MashTree

Snippy_Tree is found in a different repository so these tasks have not yet been added there.

**Comment by sage-wright** [comment]
Changes to Snippy_Tree have been made and can be found in [this PR](https://github.com/theiagen/public_health_bioinformatics/pull/19). Testing still required.

**Comment by sage-wright** [comment]
Successful tests:
- [ ] Core_Gene_SNP
- [x] MashTree_FASTA
- [x] kSNP3

**Review by emmadoughty — CHANGES_REQUESTED** [review]
It's great to see the results of this PR. It's made some big improvements! Wel done! I have a few suggestions that you will see below.

**Tests undertaken**
- OR_PHL_Acinetobacter dataset analyzed with the kSNP3 workflow 30.01.23

**Inputs**
- Can we make the input to “data_summary_column_names” comma-separated to standardize with Snippy_variants wf?
- Could we remove the “perform_data_summary” input variable and instead set this to be true within the workflow whenever the “data_summary_column_names” is completed?
- What is “input_table” for?

**Outputs**

- There’s a lot of redundancy in the current outputs
    - **Keep**
        - ksnp3_core_midpoint_snp_matrix
        - ksnp3_core_midpoint_tree
        - ksnp3_pan_midpoint_snp_matrix
        - ksnp3_pan_midpoint_tree
        - ksnp3_summarized_data
        - ksnp3_core_vcf
        - ksnp3_docker
        - ksnp3_snp_dists_version
        - ksnp3_wf_analysis_date
    - **Remove**
        - ksnp3_core_snp_matrix
        - ksnp3_core_tree
        - ksnp3_pan_snp_matrix
        - Whichever pan tree has been rerooted can also be removed:
            - ksnp3_ml_tree
            - ksnp3_nj_tree
            - ksnp3_pan_parsimony_tree
            - Why would you need these trees in addition to the core and pan-trees provided above?
    - The output file names are very long These can be shortened by removing “midpoint” and “ordered” on every occasion where they are included
    - ksnp3_ml_tree and ksnp3_nj_tree output attributes were not populated by the workflow. I couldn’t see an optional input to make these. What are they for? Can they be removed?
    - When multiple output fields (columns) are summarized, the values across all of the input columns are getting mixed together in the horizontal order of columns in the final summary csv. E.g. if you summarize a column for ARGs and a column for plasmids, all of the ARG columns in the summary csv are not grouped together, but instead interspersed with the plasmid columns.
    - Should there be a “ksnp3_core_vcf” output?
    - For the data summarization, when the data is absent or “false”, could we leave the cell blank in the summary csv? This will be much easier to interpret

I have *not* reviewed the code in this PR

**Comment by michellescribner** [comment]
>   * **Remove**
>     
>     * ksnp3_core_snp_matrix
>     * ksnp3_core_tree
>     * ksnp3_pan_snp_matrix
>     * Whichever pan tree has been rerooted can also be removed:
>       
>       * ksnp3_ml_tree
>       * ksnp3_nj_tree
>       * ksnp3_pan_parsimony_tree
>       * Would you need these trees in addition to the core and pan-trees provided above?
>   * The output file names are very long These can be shortened by removing “midpoint” and “ordered” on every occasion where they are included
>   * ksnp3_ml_tree and ksnp3_nj_tree output attributes were not populated by the workflow. I couldn’t see an optional input to make these. What are they for? Can they be removed?
>   * When multiple output fields (columns) are summarized, the values across all of the input columns are getting mixed together in the horizontal order of columns in the final summary csv. E.g. if you summarize a column for ARGs and a column for plasmids, all of the ARG columns in the summary csv are not grouped together, but instead interspersed with the plasmid columns.
>   * Should there be a “ksnp3_core_vcf” output?
>   * For the data summarization, when the data is absent or “false”, could we leave the cell blank in the summary csv? This will be much easier to interpret
> 
> I have _not_ reviewed the code in this PR

**Comment by michellescribner** [comment]
@emmadoughty The ksnp3_ml_tree and ksnp3_nj_tree outputs were added in v1.1.0. They are optional and are generated with a corresponding argument added to the "ksnp3_args" input parameter.

Also, with regard to rooting trees at the midpoint above: if a user included an ancestral genome in their kSNP3 run, could they still root the tree at this sample in later analysis if the output is a midpoint-rooted tree? I just want to make sure that outputting a midpoint-rooted tree won't cause any problems if the user has a different sample they want to use as the root.

**Comment by emmadoughty** [comment]
Thanks for the clarification about the ml and NJ trees. :) 

The midpoint rooting on the tree won't prevent the user rerooting the tree again. Rerooting essentially just reorders the file, regardless of whether this is done programmatically, as in this workflow, or via software like FigTree or iToL. You can reorder that file as many times as you like

**Comment by sage-wright** [comment]
Great comments, Emma!

Response:
- `column_names` is now comma-delimited
- `perform_data_summary` boolean has been removed and instead just checks for presence of text in `column_names`
- `input_table` is required for command-line testing. it has no usage for Terra, but is necessary for development

- all unordered matrices and unrooted trees are no longer being returned as output to Terra for kSNP3 or Core_Gene_SNP
  - since the unordered matrices and unrooted trees are no longer being output, I've removed "ordered" and "midpoint" text from the remaining output variables
- when a cell contains "False" it now will be empty
- values across column_names should now be grouped together by those column_names

**Review by emmadoughty — CHANGES_REQUESTED** [review]
Thanks for making these changes, Sage! 

**Tests undertaken**

OR_PHL_Acinetobacter dataset with 

- kSNP3: [https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Doughty_Sandbox/job_history/f3dba9d8-cd22-4fc7-b357-29ead10c5bc4](https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Doughty_Sandbox/job_history/f3dba9d8-cd22-4fc7-b357-29ead10c5bc4)
- mashtree_FASTA: [https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Doughty_Sandbox/job_history/f3dba9d8-cd22-4fc7-b357-29ead10c5bc4](https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Doughty_Sandbox/job_history/f3dba9d8-cd22-4fc7-b357-29ead10c5bc4)
- Core_gene_SNP: [https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Doughty_Sandbox/job_history/4c53b7f4-80b8-47d1-bc8c-0c46a4089e13](https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Doughty_Sandbox/job_history/4c53b7f4-80b8-47d1-bc8c-0c46a4089e13)

**Workflow completion**

- kSNP3, Mashtree and Core_gene_SNP workflows completed successfully ✅

**Inputs**

- Could we change “data_summary_sample_names” to simply “samplename” as in other workflows to make it more intuitive for users? This is applicable to Mashtree and Core_gene_SNP workflows only
- All other input variables look good ✅

**Outputs**

- “midpoint” can be removed from all output file names and output variable names throughout all workflows
- It might be helpful to give the option to prefix the summarised_data file to make it more identifiable after download.
- Mashtree workflow:
    - Tip labels on tree have “_contigs” suffix. This does not match with the sample names used in the summarized_data.csv and distance_matrix so they cannot be visualised in phandango. Removing the “_contigs” suffix on the tree tip labels will fix this
    - Mash distance matrix is not formatted for use with phandango (tsv should be converted to csv, and phandango suffixes “:c1” needs to be appended to column names). Assuming tree tip labels will not contain “_contigs”, this will also need to be removed from rows and columns.
    - Matrix has not been reordered to match tree tip order
- Ouputs from kSNP3 and Core_gene_SNP are great!

**Code review**

I have *not* reviewed the code for this PR

Further review will be needed after addressing comments re. Mashtree

**Comment by sage-wright** [comment]
Most all of the applied changes requested:
- all instances of `data_summary_sample_names` have been changed to `sample_names`
- "midpoint" and "ordered" have been removed from all output file names and output variable names. 
  - the `reorder_matrix` task has been condensed to only output the midpoint-rooted matrix and tree and renamed the output files accordingly
-  the "summarized_data.csv" is now prefixed with the "cluster_name" given with each workflow
- Mashtree:
  - I was never actually using the `reorder_matrix` task in Mashtree: that has been fixed
    - this now means the distance matrix is reordered, a csv, and now has phandango coloring
  - still working on the "_contigs' suffix--not 100% sure how to do this because there's no easy way to rename the terminal ends of a tree according to my searches. Will provide updates.

**Review by emmadoughty — APPROVED** [review]
I have re-run the Mashtree workflow and confirm the results look great! Fantastic work getting this done, Sage, and thanks for such a quick turnaround time with this, especially in the last day or two!

**Review by kevinlibuit — APPROVED** [review]
Well done!

**Pull request merged**
