### PR TITLE
Eld docs dev

### PR DESCRIPTION
**Pull request by emmadoughty**
This PR makes a few changes as detailed below:

* task_screen.wdl: Amended so the PE wf checks the number of reads in read1 and read2 files **combined** is greater than `min_reads`, rather than either/both read1 or read2 files needing to have more reads than `min_reads`. The `min_reads` default value is set with a default of 7472 for both the PE and SE wf. 
* task_screen.wdl: Amended `percent_reads` to be calculated as a percentage rather than a ratio x100.
* task_screen.wdl: Amended read flag text to include variable `min_proportion`, rather than default value "50" in the flag text.
* task_screen.wdl: Amended so the PE wf checks the number of bp in read1 and read2 files **combined** is greater than `min_basepairs`, rather than either/both read1 or read2 files needing to have more basepairs than `min_basepairs`.
* theiaprok_illumina_pe.wdl: Amended default value for `min-proportion` to be 40, as 50% of reads in the forward and reverse files might be too strict a cut-off. 
* task_trimmomatic.wdl: Amended default values set in task_trimmomatic.wdl to match those set in wf_read_QC_trim.wdl simply to avoid confusion over which values are being used as default.

I hope this is clear. Do let me know if you have any questions. 

To note, the commit history for this PR is a mess so I recommend you don't look at it! :|

### CODE REVIEW

**Comment by michellescribner** [comment]
Thank you for amending the default values in the trimmomatic task - meant to do that when I amended the values in the read_QC_trim workflow. We should also amend the values in the trimmomatic se task

**Comment by michellescribner** [comment]
Testing on https://console.cloud.google.com/storage/browser/fc-1162d2b8-109d-42a8-b1b0-c05141aa98ad/submissions/f2237dcb-b724-4e0e-a845-8155f02a57fd?authuser=michelle.scribner@theiagen.com

**Comment by michellescribner** [comment]
Review:
- Code changes look good 
- TheiaProk_Illumina_PE workflow runs successfully on Terra

Verified through testing:
- min_reads fail
- min_genome_size and max_genome_size fail
- est cov fail

Note: Trimmomatic ran using the former default trimming parameters, not those indicated in this dev branch, because the read_QC_trim wf on this branch overrode the updated values in the trimmomatic task.

**Comment by kevinlibuit** [comment]
Updated to sync trimmomatic task defaults with most recent commit to main (i.e. [modification of trimming params](https://github.com/theiagen/public_health_bacterial_genomics/commit/e744fd71ce5511dc80c40ca044be606c97424b42)).

**Review by kevinlibuit — APPROVED** [review]

**Comment by kevinlibuit** [comment]
> Review:
> 
> * Code changes look good
> * TheiaProk_Illumina_PE workflow runs successfully on Terra
> 
> Verified through testing:
> 
> * min_reads fail
> * min_genome_size and max_genome_size fail
> * est cov fail
> 
> Note: Trimmomatic ran using the former default trimming parameters, not those indicated in this dev branch, because the read_QC_trim wf on this branch overrode the updated values in the trimmomatic task.

Clarifying for posterity: 
_I modified the qc criteria so that certain samples would be expected to fail or pass, and verified that I got the expected result. For example if the sample had a genome size of 1,000,000 I intentionally set the max genome size to 2 and made sure it failed_

**Pull request merged**
