### PR TITLE
Gambit 0.4

### PR DESCRIPTION
**Pull request by jlumpe**
This adds tentative support for GAMBIT 0.4 (currently `0.4.0b1`). Don't merge until `quay.io/staphb/gambit:0.4.0` docker image is actually available.

### CODE REVIEW

**Comment by jlumpe** [comment]
@kevinlibuit

**Comment by kevinlibuit** [comment]
@jlumpe I see that 0.4.0 is still tagged as a pre-release. Once the release is made, I can write the staphb/gambit:0.4.0 dockerfile and work with @kapsakcj to get that hosted on StaPH-B's quay and dockerhub repo

**Comment by jlumpe** [comment]
`0.4.0` release is finalized.

**Comment by kevinlibuit** [comment]
@jlumpe these look great! Going to merge this one and close #29 as it seems this PR incorporates all the suggested changes there.

**Pull request merged**
